version: '3.5'
services:
 nginx:
      image: nginx
      container_name: production_nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf 
      ports: 
        - 80:80
      depends_on:
        - frontend
        - backend


 redis:
      image: redis
      ports: 
        - 6379
      container_name: container_redis
      environment:
        - REDIS=localhost
 backend:
      image: backend
      build: ./backend
      ports:
        - 3001:8000
      container_name: backend
      environment:
        - FRONT_URL=http://localhost:5001
        - REDIS=redis
        - REDIS_PORT=6379
        - DB_USERNAME=user
        - DB_PASSWORD=example
        - DB_HOST=backend_db

      depends_on:
        - redis
        - db

 frontend:
       image: frontend
       build: ./frontend
       ports:
         - 5001:5000
       container_name: frontend
       environment:
         - API_URL=http://localhost:3001

 db:
        image: postgres
        restart: unless-stopped
        environment:
          - POSTGRES_USER=user
          - POSTGRES_PASSWORD=example
        container_name: backend_db
        volumes:
          - ./database:/var/lib/postgresql/data


