version: '3.5'
services:
  backend:
    image: backend
    build: ./ml-kurkkumopo-backend
    ports: 
      - 5000:5000
    container_name: backend
    depends_on:
      - training
    volumes:
      - model:/src/model

  frontend:
     image: frontend
     build: ./ml-kurkkumopo-frontend
     ports:
       - 3000:3000
     container_name: frontend

  training:
     image: training
     build: ./ml-kurkkumopo-training
     volumes: 
         - model:/src/model
         - imgs:/src/imgs
         - data:/src/data


volumes:
  model:
  imgs:
  data:

