version: '3.5'
services:
    backend:
      image: backend
      build: ./backend
      ports:
        - 3001:8000
      environment:
        - FRONT_URL=http://localhost:5001
    frontend:
       image: frontend
       build: ./frontend
       ports:
         - 5001:5000
       environment:
         - API_URL=http://localhost:3001
